services:
  zendesk-dashboard:
    image: rickdevs/zendesk-dashboard:latest
    container_name: zendesk-dashboard
    ports:
      - "3737:3737"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ZENDESK_SUBDOMAIN=c-innovation
      - ZENDESK_OAUTH_TOKEN=seu_token_oauth_aqui
    labels:
      - "com.c-innovation.app=zendesk-dashboard"
      - "com.c-innovation.version=1.0"
